### ISSUE TITLE
database model

### ISSUE THREAD

**Issue by souzacharles** [leifeld/tnam#6]
Hello, I intend to apply the tnam package in an academic research. More precisely, in a study on international trade networks (comtrade data). Would you like to know how the database should be built? For example data.frame or list? Do you have any models? Thanks.

**Comment by leifeld** [comment]
Hi. Please make sure you understand that the way `tnam` estimates the model is through maximum pseudolikelihood (MPLE), which is likely biased to some extent (depending on the application). If there are no temporal dependencies, consider the new `BANAM` package (with Bayesian estimation). If you require temporal dependence, consider the M-STAR model (the multiparametric spatio-temporal autoregressive model). A Stata implementation is available [here](http://fmwww.bc.edu/RePEc/bocode/s/spmstard.html), but maybe R implementations exist, too. I suppose some people write this up in BUGS or Stan to be flexible.

If you still want to use `tnam`, check out the help pages for `tnam` and `tnamdata` for some examples.
